/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/man.gltf --transform
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function ManModel(props) {
  const { nodes, materials } = useGLTF('/man-transformed.glb');

  materials['White.001'].emissiveIntensity = 10;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['Man-Body'].geometry}
        material={materials['White.001']}
      />
      <mesh
        geometry={nodes['Man-Body_1'].geometry}
        material={materials['Outline.001']}
      />
    </group>
  );
}

useGLTF.preload('/man-transformed.glb');
